[package]
name = "bio_exp"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
rand = ">=0.7.3, < 0.9"
petgraph = ">=0.4, <0.7"
